"""Recordly 应用常量和版本信息"""

APP_NAME = "Recordly"
APP_VERSION = "0.3.0"
ORG_NAME = "Recordly"

# 默认窗口尺寸
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 800

# 录制参数
DEFAULT_FPS = 30
DEFAULT_BITRATE = "10M"
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_AUDIO_CHANNELS = 2

# 时间线
DEFAULT_TRACK_HEIGHT = 40
DEFAULT_RULER_HEIGHT = 30
TIMELINE_PIXELS_PER_SECOND = 100
